#!/usr/bin/env bash

if [ "z${MBDEBUG}" != "z" ]; then
  set -x
fi

base=$(realpath $(dirname $0))
ve="$base/dep/ve"
py="${ve}/bin/python"
pip="${py} -m pip --use-feature=2020-resolver"
cd "$base"
# Clean old installations
rm -rf $base/dep/ve{2,3}
git submodule init
git submodule update
$(which python3) -m venv "${ve}"
if ! which afew
then
  cd "dep/afew"
  "${py}" setup.py install
fi
cd "$base"
${pip} install -r src/requirements.txt
if [ "z${MBDEV}" != "z" ]; then
  ${pip} install git+https://github.com/OfflineIMAP/offlineimap3.git@next
else
  ${pip} install offlineimap
fi

# vim: set et ts=2 sts=0 sw=0:
