#!/usr/bin/env bash

base=$(realpath $(dirname $0))
ve="$base/dep/ve2"
vethree="$base/dep/ve3"
py="${ve}/bin/python"
pythree="${vethree}/bin/python"
pipthree="${vethree}/bin/pip"
pip="${ve}/bin/pip"
cd "$base"
git submodule init
git submodule update
virtualenv -p $(which python2) --no-site-packages "$ve"
virtualenv -p $(which python3) --no-site-packages "$vethree"
py3version=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
ln -s /usr/lib/python${py3version}/site-packages/notmuch "${vethree}/lib/python${py3version}/site-packages/"
cd "dep/afew"
"${pythree}" setup.py install
cd "$base"
"${pip}" install -r src/requirements.txt

