#!/usr/bin/env bash

if [ "z${MBDEBUG}" != "z" ]; then
  set -x
fi

base=$(realpath $(dirname $0))
ve="$base/dep/ve3"
py="${ve}/bin/python"
pip="${py} -m pip --use-feature=2020-resolver"
cd "$base"
# Clean old installations
rm -rf $base/dep/ve{2,3}
git submodule init
git submodule update
$(which python3) -m venv "${ve}"

# afew
if ! which afew
then
  cd "dep/afew"
  "${py}" setup.py install
fi
cd "$base"
${pip} install -r src/requirements.txt

# papero
PAPEROPATH="dep/papero"
if ! [ -d $PAPEROPATH ]; then
  git clone https://git.sr.ht/~blallo/papero $PAPEROPATH
  cd $PAPEROPATH
else
  cd $PAPEROPATH
  git pull
fi
go build -v -o ../ ./cli/paperod/...
cd ../..

# vim: set et ts=2 sts=0 sw=0:
