#!/usr/bin/env bash

PACKAGES="
python2.7
python-jinja2
mutt
notmuch
afew
realpath
offlineimap
msmtp
python-notmuch
dbacl
python-dev
python-setuptools
zsh
tmux
urlview
"
apt-get -q install -y $PACKAGES
