#!/usr/bin/env bash
### simple wrapper for notmuch
if [[ -z "$MAIL_ENV" ]]; then
	source $(readlink -f $(dirname $0)/../activate)
fi

wrappers_dir=$(readlink -f $(dirname $0))
PATH=:$PATH:
PATH=${PATH//:$wrappers_dir:/:}
PATH=${PATH#:}
PATH=${PATH%:}
export PATH

mutt -F "${MAIL_ENV}/muttrc" "$@"
