#!/usr/bin/env bash

if ! which notify-send > /dev/null 2>&1; then
    # missing notify-send
    exit 0
fi

if [ "z${DISPLAY}" = "z" ] && [ "z${WAYLAND_DISPLAY}" = "z" ]; then
    # missing graphic environment
    exit 0
fi

basedir="$(readlink -f "$(dirname "$0")/../../")"
#shellcheck source=../activate
source "$(readlink -f "$basedir/activate")"
mailparse=(mailparse --mail-address realname-or-address)

function parse_and_notify() {
    to=$(echo "${1}"|"${mailparse[@]}" --header To)
    from=$(echo "${1}"|"${mailparse[@]}" --header From)
    sub=$(echo "${1}"|mailparse --header Subject)
    notify-send "New mail" "<b>To:</b> ${to}\n<b>From:</b> ${from}\n<b>Sub:</b> ${sub}"
}

if [ "${1}" != "" ]
then
    parse_and_notify "${1}"
else
    while read line
    do
        parse_and_notify "$(notmuch show --format=raw $line)"
    done
fi
