[groups.pgp-valid]
pgp_validity = ["f"]

[groups.academia]
to_domains = [
    ".*mit.edu",
    "oxford.uk",
]
to = ["myprof@herdomain.us"]

[groups.mycrew]
to = [
    "joe@yeah.com",
    "mina@mazzini.it",
]

[groups.ecommerce]
to_domains=[
    "ebay.com",
    "buyalot.com",
]
