[[hooks]]
group = "academia"
[hooks.rules]
sign = false
encrypt = false
from = "Name Surname <name.surname@mit.edu>"

[[hooks]]
group = "mycrew"
[hooks.rules]
encrypt = true
from = "Anon Me <me.in@disgui.se>"

[[hooks]]
group = "pgp-valid"
[hooks.rules]
encrypt = true

[[hooks]]
group = "ecommerce"
# Let's demote things from those domains
score=-10
